using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DiffusionNexus.UI.Services.Engine;

/// <summary>
/// A model library the engine should read, together with the folder names that library uses.
/// </summary>
/// <param name="BasePath">The library root (a registered Base Model Folder).</param>
/// <param name="Categories">
/// The library's own category mapping, copied from the installation that declared it. Empty means
/// "uses ComfyUI's standard folder names", which is the case for a plain <c>…/ComfyUI/models</c>.
/// </param>
public sealed record EngineModelRoot(string BasePath, IReadOnlyList<ComfyCategoryPath> Categories);

/// <summary>
/// Composes the engine's <c>extra_model_paths.yaml</c> from every registered Base Model Folder.
///
/// <para>
/// The engine is app-owned and installs no models of its own — the whole point is that it reads
/// the libraries the user already has. The SDK's installer can only wire a <em>single</em>
/// <c>ModelBaseFolder</c>, so an install left every folder but the first invisible to the engine,
/// and a user whose models live in the second folder got a workload that reported nothing
/// installed and a ComfyUI that genuinely could not load anything.
/// </para>
///
/// <para>
/// Output is deterministic — no timestamp — so callers can compare it against the file on disk and
/// only write when something actually changed.
/// </para>
/// </summary>
public static class EngineModelPathsFile
{
    /// <summary>
    /// ComfyUI's standard folder names, used for a root that brings no mapping of its own. This is
    /// the same set the SDK's own generator emits, so a single-root engine ends up with the same
    /// wiring it had before.
    /// </summary>
    public static IReadOnlyList<string> DefaultCategories { get; } =
    [
        "audio_encoders", "checkpoints", "clip", "clip_vision", "configs", "controlnet",
        "diffusers", "diffusion_models", "embeddings", "gligen", "grounding-dino",
        "hypernetworks", "inpaint", "ipadapter", "latent_upscale_models", "loras",
        "model_patches", "photomaker", "sams", "style_models", "text_encoders", "unet",
        "upscale_models", "vae", "vae_approx"
    ];

    // ASCII only, deliberately: ComfyUI has read this file with the process default encoding in
    // some versions, so a non-ASCII character here would come back as mojibake on Windows.
    private const string Header = """
        # Generated by Diffusion Nexus - DO NOT EDIT.
        #
        # This file is rewritten from Settings -> Model Storage Folders every time the engine
        # starts, so any hand edit here is lost. Add or remove folders in Settings instead.
        #
        # One section per registered model folder. Category names are copied from the ComfyUI
        # installation that declared the folder, because a shared library does not have to use
        # ComfyUI's own folder names.
        """;

    /// <summary>
    /// The full file content for <paramref name="roots"/>, in order (the starred default first —
    /// ComfyUI searches the sections in the order they appear).
    /// </summary>
    public static string Compose(IReadOnlyList<EngineModelRoot> roots)
    {
        ArgumentNullException.ThrowIfNull(roots);

        var builder = new StringBuilder();
        builder.Append(Header).Append('\n');

        var index = 0;
        foreach (var root in roots)
        {
            if (string.IsNullOrWhiteSpace(root.BasePath))
            {
                continue;
            }

            index++;

            foreach (var (suffix, categories) in Layers(root))
            {
                builder.Append('\n');
                builder.Append($"dn_models_{index}{suffix}:").Append('\n');
                builder.Append($"    base_path: {ToYamlPath(root.BasePath)}").Append('\n');

                foreach (var category in categories)
                {
                    builder.Append($"    {category.Category}: {ToYamlPath(category.Value)}").Append('\n');
                }
            }
        }

        return builder.ToString();
    }

    /// <summary>
    /// Splits a root into one or more sections, each holding at most one path per category.
    ///
    /// A source yaml may map one category onto several folders via a block scalar
    /// (<c>loras: |</c> followed by two paths). Re-emitting that as a block scalar would work for
    /// ComfyUI but not for our own line-based readers, which would see the key with an empty
    /// value and silently drop every path under it — the workload check would then report models
    /// missing that the engine can load perfectly well. Emitting one extra section per surplus
    /// value keeps every line a plain <c>key: value</c>, which both readers agree on.
    /// </summary>
    private static IEnumerable<(string Suffix, IReadOnlyList<ComfyCategoryPath> Categories)> Layers(
        EngineModelRoot root)
    {
        if (root.Categories.Count == 0)
        {
            yield return (string.Empty, [.. DefaultCategories.Select(c => new ComfyCategoryPath(c, c + "/"))]);
            yield break;
        }

        // Grouped, preserving the order categories first appear in the source file.
        var grouped = root.Categories
            .GroupBy(c => c.Category, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var depth = grouped.Max(g => g.Count());

        for (var layer = 0; layer < depth; layer++)
        {
            var slice = grouped
                .Select(g => g.ElementAtOrDefault(layer))
                .Where(c => c is not null)
                .Select(c => c!)
                .ToList();

            if (slice.Count == 0)
            {
                continue;
            }

            yield return (layer == 0 ? string.Empty : $"_alt{layer}", slice);
        }
    }

    /// <summary>
    /// Forward slashes, as ComfyUI's sample file and the SDK's generator both use. Backslashes in
    /// a plain (unquoted) yaml scalar are literal, so either form loads — but a Windows path is
    /// far easier to misread with escapes in it, and the SDK already settled on this shape.
    /// </summary>
    private static string ToYamlPath(string path) => path.Replace('\\', '/');
}
