namespace DiffusionNexus.UI.Services.Licensing;

/// <summary>
/// One third-party component and the licence it was received under.
/// </summary>
/// <remarks>
/// Generated by Scripts/Generate-ThirdPartyNotices.ps1 into third-party-notices.json and
/// embedded at build time. Every string is non-null; absent values are empty.
/// </remarks>
public sealed record ThirdPartyComponent(
    string Id,
    string Version,
    string License,
    string Copyright,
    string Authors,
    string ProjectUrl,
    string LicenseText)
{
    /// <summary>The attribution line to display: the declared copyright, or one built from the authors.</summary>
    public string Attribution =>
        !string.IsNullOrWhiteSpace(Copyright) ? Copyright
        : !string.IsNullOrWhiteSpace(Authors) ? $"Copyright (c) {Authors}"
        : "(no copyright notice declared)";

    /// <summary>Id and version as one label, for list rows.</summary>
    public string DisplayName =>
        string.IsNullOrWhiteSpace(Version) ? Id : $"{Id}  {Version}";
}
