// <auto-generated />
using System;
using DiffusionNexus.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiffusionNexus.DataAccess.Migrations.Core
{
    [DbContext(typeof(DiffusionNexusCoreDbContext))]
    [Migration("20260108231330_AddMaxBackupsSetting")]
    partial class AddMaxBackupsSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoBackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoBackupIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoBackupIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoBackupLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasetStoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteEmptySourceFolders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedCivitaiApiKey")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GenerateVideoThumbnails")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastBackupAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoraSortSourcePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoraSortTargetPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBackups")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MergeLoraSources")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowNsfw")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowVideoPreview")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseForgeStylePrompts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.Creator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Creators", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.DatasetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppSettingsId");

                    b.HasIndex("Name");

                    b.ToTable("DatasetCategories", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.DisclaimerAcceptance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WindowsUsername");

                    b.ToTable("DisclaimerAcceptances", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.LoraSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppSettingsId");

                    b.HasIndex("FolderPath");

                    b.ToTable("LoraSources", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowCommercialUse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowDerivatives")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDifferentLicense")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowNoCredit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CivitaiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPoi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CivitaiId")
                        .IsUnique()
                        .HasFilter("[CivitaiId] IS NOT NULL");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CivitaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashAutoV1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashAutoV2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashBLAKE3")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashCRC32")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSHA256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocalFileValid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LocalFileVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PickleScanMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PickleScanResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Precision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("SizeKB")
                        .HasColumnType("REAL");

                    b.Property<string>("SizeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("VirusScanResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CivitaiId");

                    b.HasIndex("FileSizeBytes");

                    b.HasIndex("HashSHA256");

                    b.HasIndex("LocalPath");

                    b.HasIndex("ModelVersionId");

                    b.ToTable("ModelFiles", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlurHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CachedFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CfgScale")
                        .HasColumnType("REAL");

                    b.Property<long?>("CivitaiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DenoisingStrength")
                        .HasColumnType("REAL");

                    b.Property<string>("GenerationModel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocalCacheValid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalCachePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NegativePrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NsfwLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sampler")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Steps")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ThumbnailData")
                        .HasColumnType("BLOB");

                    b.Property<int?>("ThumbnailHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailMimeType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThumbnailWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CivitaiId");

                    b.HasIndex("ModelVersionId");

                    b.HasIndex("ModelVersionId", "SortOrder");

                    b.ToTable("ModelImages", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelTag", b =>
                {
                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModelId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ModelTags", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseModelRaw")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CivitaiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EarlyAccessDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThumbsDownCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThumbsUpCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseModel");

                    b.HasIndex("CivitaiId")
                        .IsUnique()
                        .HasFilter("[CivitaiId] IS NOT NULL");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelVersions", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.TriggerWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelVersionId");

                    b.ToTable("TriggerWords", (string)null);
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.DatasetCategory", b =>
                {
                    b.HasOne("DiffusionNexus.Domain.Entities.AppSettings", "AppSettings")
                        .WithMany("DatasetCategories")
                        .HasForeignKey("AppSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppSettings");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.LoraSource", b =>
                {
                    b.HasOne("DiffusionNexus.Domain.Entities.AppSettings", "AppSettings")
                        .WithMany("LoraSources")
                        .HasForeignKey("AppSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppSettings");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.Model", b =>
                {
                    b.HasOne("DiffusionNexus.Domain.Entities.Creator", "Creator")
                        .WithMany("Models")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelFile", b =>
                {
                    b.HasOne("DiffusionNexus.Domain.Entities.ModelVersion", "ModelVersion")
                        .WithMany("Files")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelImage", b =>
                {
                    b.HasOne("DiffusionNexus.Domain.Entities.ModelVersion", "ModelVersion")
                        .WithMany("Images")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelTag", b =>
                {
                    b.HasOne("DiffusionNexus.Domain.Entities.Model", "Model")
                        .WithMany("Tags")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiffusionNexus.Domain.Entities.Tag", "Tag")
                        .WithMany("Models")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelVersion", b =>
                {
                    b.HasOne("DiffusionNexus.Domain.Entities.Model", "Model")
                        .WithMany("Versions")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.TriggerWord", b =>
                {
                    b.HasOne("DiffusionNexus.Domain.Entities.ModelVersion", "ModelVersion")
                        .WithMany("TriggerWords")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.AppSettings", b =>
                {
                    b.Navigation("DatasetCategories");

                    b.Navigation("LoraSources");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.Creator", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.Model", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.ModelVersion", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Images");

                    b.Navigation("TriggerWords");
                });

            modelBuilder.Entity("DiffusionNexus.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
