using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using DiffusionNexus.UI.Classes;
using DiffusionNexus.LoraSort.Service.Classes;
using DiffusionNexus.LoraSort.Service.Services;

namespace DiffusionNexus.UI.ViewModels;

public partial class LoraHelperViewModel : ViewModelBase
{
    // This is the backing list of *all* cards
    private readonly List<LoraCard> _allCards = new();

    [ObservableProperty]
    private string? searchText;

    // What the View actually binds to
public ObservableCollection<LoraCard> Cards { get; } = new();
public ObservableCollection<FolderItemViewModel> FolderItems { get; } = new();
private readonly ISettingsService _settingsService;
public LoraHelperViewModel() : this(new SettingsService())
{
}

public LoraHelperViewModel(ISettingsService settingsService)
{
    _settingsService = settingsService;
    Load();
}

private void Load()
{
    var settings = _settingsService.LoadAsync().GetAwaiter().GetResult();
    if (string.IsNullOrWhiteSpace(settings.LoraHelperFolderPath))
        return;

    var discovery = new ModelDiscoveryService();
    var rootNode = discovery.BuildFolderTree(settings.LoraHelperFolderPath);
    FolderItems.Clear();
    foreach (var child in rootNode.Children)
        FolderItems.Add(ConvertFolder(child));

    foreach (var model in discovery.CollectModels(settings.LoraHelperFolderPath))
    {
        var card = new LoraCard
        {
            Name = model.ModelName,
            Model = model
        };
        _allCards.Add(card);
    }

    RefreshCards();
}

private FolderItemViewModel ConvertFolder(FolderNode node)
{
    var vm = new FolderItemViewModel { Name = node.Name, ModelCount = node.ModelCount };
    foreach (var child in node.Children)
        vm.Children.Add(ConvertFolder(child));
    return vm;
}

    // 3) This partial method is generated by [ObservableProperty];
    //    it runs whenever SearchText is set.
    partial void OnSearchTextChanged(string? value)
    {
        RefreshCards();
    }

    private void RefreshCards()
    {
        // filter (case-insensitive) if there's any text, otherwise show all
        var query = string.IsNullOrWhiteSpace(SearchText)
            ? _allCards
            : _allCards.Where(c =>
                c.Name?.Contains(SearchText!, StringComparison.OrdinalIgnoreCase) == true);

        // rebuild the ObservableCollection
        Cards.Clear();
        foreach (var c in query)
            Cards.Add(c);
    }
}


public partial class LoraCard : ViewModelBase
{
    [ObservableProperty]
    private string? _name;

    [ObservableProperty]
    private string? _description;

    [ObservableProperty]
    private ModelClass? _model;

    public string? GetPreviewImagePath()
    {
        if (Model == null) return null;
        string[] priority = [
            ".preview.png",
            ".preview.webp",
            ".preview.jpeg",
            ".preview.jpg"
        ];

        foreach (var ext in priority)
        {
            var file = Model.AssociatedFilesInfo.FirstOrDefault(f => f.Name.EndsWith(ext, StringComparison.OrdinalIgnoreCase));
            if (file != null)
                return file.FullName;
        }
        return null;
    }
}
